[package]
name = "load-balancer"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
crossterm = "0.29.0"
rand = "0.9.2"
ratatui = "0.29.0"
tokio = { version = "1.47.1", features = ["full"] }
